### PR TITLE
Refactor footer qrcode

### PR DESCRIPTION
**Pull request by sderacy**
Changes the QR code page to use the footer and css partials since those were merged before Leah could merge her code.

I noticed that some of the css wasn't being transferred and that is because you need to serve the css page to each route. There's gotta be a faster way but this is a quick fix just to show what the application should look like with all the new changes.

If you can figure out a more optimal way to serve the common css file feel free to push a commit to fix that.

Test this on your side.

### CODE REVIEW

**Comment by paytonshaltis** [comment]
> If you can figure out a more optimal way to serve the common css file feel free to push a commit to fix that.

Out now, but I think I do know the solution. Will try when I’m back home.

**Comment by sderacy** [comment]
I had some downtime so I looked up the solution and it looks like it works now. Much less files needed to be changed and I got to clean up code elsewhere whilst doing this

**Comment by sderacy** [comment]
If it looks good on your side, feel free to approve it AND merge it since I will be out for a bit.

Thanks!

**Comment by paytonshaltis** [comment]
Yeah, the solution I was going to try was to just serve it from the static folder which I see you did. I saw at some point you had a dedicated route for it but it definitely makes more sense to just have it in that common folder. Even if someone gets access to it, its just a stylesheet.

Going to approve and merge it now.

**Review by paytonshaltis — APPROVED** [review]

**Pull request merged**
