### PR TITLE
Add theme settings

### LINKED ISSUE #8: Allow color scheme change
It'd be nice to let the user pick between different themes, such as dark mode and light mode.

### LINKED ISSUE #92: Implement Theme
Allow user to choose between light and dark mode

### LINKED ISSUE #129: Change font size naming for Settings page
It's set to "smaller, medium, larger" because that's the name of the values that are being applied to font size, but replacing with something more readable might be better for the user

### PR DESCRIPTION
**Pull request by sderacy**
Closes #8, Closes #92, Closes #129 

This implements the light mode/dark mode setting by changing all of the text colors on the page to a scheme of white and gold or gold and navy blue.

There is an issue currently where when clicking on the link or refreshing, everything turns light gold. I'm looking into it.

### CODE REVIEW

**Comment by sderacy** [comment]
I was going to put contrast in this branch but since I'm changing so many files, I think I'd save this for after this branch gets merged. Let me know what you guys think though.

@matyis1 @lelekaz @paytonshaltis @thadakn1

**Comment by paytonshaltis** [comment]
> I was going to put contrast in this branch but since I'm changing so many files, I think I'd save this for after this branch gets merged. Let me know what you guys think though.
> 
> @matyis1 @lelekaz @paytonshaltis @thadakn1

I'll take a look at this tomorrow as well as #130 and get back to you!

**Comment by paytonshaltis** [comment]
Just pushed a commit that shows the user the results of their changes settings (everything but their name) instantly. When a user chooses a setting that changes how content is displayed, it is done instantly to show them a preview of it. They still have to decide to either submit or cancel changes, but now they can see what their changes will do.

Test it out on your end and see what happens @sderacy @lelekaz @matyis1 @thadakn1, but it seems to be working pretty well. Contrast obviously doesn't do anything, and some of the fonts are very similar (Helvetica and Sans-Serif)

**Comment by sderacy** [comment]
@paytonshaltis Looks good!

Are we trying to fix the bug in this PR too? I know you mentioned moving the templates but I want to know if I should merge this right away when this gets approved.

**Comment by paytonshaltis** [comment]
I would say merge this now, I'll make a separate issue for the bug we were talking about. I'll approve this PR.

**Review by paytonshaltis — APPROVED** [review]

**Pull request merged**
