### PR TITLE
Better login

### PR DESCRIPTION
**Pull request by paytonshaltis**
Adds server and client-side login modifications:

- Adds a second password field in the account creation
- Prevents the user from submitting either form unless all fields are filled out, emails are actual emails, passwords are at least 8 characters long, and passwords match in account creation.
- Adds appropriate error messages for login or signup failure.
- On login or signup failure, any form data the user submits will be preserved.

### CODE REVIEW

**Comment by sderacy** [comment]
Quick question, is this supposed to be merged before or after this PR? https://github.com/sderacy/gooncard/pull/19

**Comment by sderacy** [comment]
> > Quick question, is this supposed to be merged before or after this PR? #19
> 
> I think they can be merged in either order, but I would do the db one first.

Gotcha, I've run into an issue with the disabled buttons code which might be related to cookies but there's also a styling issue here as well so I think it'd be good to merge PR #19 first

Lemme know when you do so we can look at this one too

**Comment by paytonshaltis** [comment]
> > > Quick question, is this supposed to be merged before or after this PR? #19
> > 
> > 
> > I think they can be merged in either order, but I would do the db one first.
> 
> Gotcha, I've run into an issue with the disabled buttons code which might be related to cookies but there's also a styling issue here as well so I think it'd be good to merge PR #19 first
> 
> Lemme know when you do so we can look at this one too

What's the issue you're having with the button? I just tried it again on my other computer and its working for me.

**Comment by sderacy** [comment]
> What's the issue you're having with the button? I just tried it again on my other computer and its working for me.

I booted up the server and ran npm install + npm start. The issue I was noticing was that the register / login button was disabled on startup even after entering valid fields.

I actually fixed it by removing node modules so it might've just been previous packages hadn't updated

The other issue is that the additional field is making the form big enough to be scrollable and it looks like this:
image

**Comment by sderacy** [comment]
Gotcha, I'll cross that bridge when we get there so I'll make that an issue and you should be good to go.

We also might wanna consider making the disabled button a different color so it's more obvious that it's disabled.

That's a big nitpick though.

Good work!

**Review by sderacy — APPROVED** [review]

**Pull request merged**
