### PR TITLE
Removed value from homepage

### PR DESCRIPTION
**Pull request by thadakn1**
For the Home page, I removed the value of the instagram handle to clean up interface. The user should not have to see their account handle/username again when it's already in the Profile page. This is just repeated information.

### CODE REVIEW

**Comment by sderacy** [comment]
Thoughts @matyis1 @lelekaz @paytonshaltis ?

Personally, I love it.

**Comment by sderacy** [comment]
Also @thadakn1 I had to push some code to this branch because there was a merge conflict. It looks like it's been fixed now but just a heads up in case you want to keep adding to it.

**Review by sderacy — APPROVED** [review]
I like this change! It looks cleaner and I can't think of any harm this introduces but I'm open to other feedback.

**Comment by thadakn1** [comment]
nope, you can merge the change @sderacy , im not adding anything to this branch anymore

**Comment by thadakn1** [comment]
also thank you!

**Comment by paytonshaltis** [comment]
> Thoughts @matyis1 @lelekaz @paytonshaltis ?

Yes, I totally agree. Only need to show the user what they really need; having label and value is definitely redundant.

**Pull request merged**
