### PR TITLE
Implemented the speech recognition on the homepage

### PR DESCRIPTION
**Pull request by lelekaz**
Needs some front-end facelifting, but the functionality is there.
DO NOT PUSH because we can save it for the final milestone (don't want to be done too early because then Salgian will tell us to do more 😂)

### CODE REVIEW

**Comment by lelekaz** [comment]
> …end facelifting, but the functionality is there. DO NOT PUSH because we can save it for the final milestone (don't want to be done too early because then Salgian will tell us to do more 😂)

https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339
Utilize these steps to allow your website to enable your microphone.

**Comment by sderacy** [comment]
@lelekaz @thadakn1 @paytonshaltis @matyis1 

I pushed up most of the changes we talked about aside from the shortcut commands. I'm still ambivalent on the discussion of whether they're needed so if we decide not to implement it, that's also fine.

**Comment by thadakn1** [comment]
looks good! it worked fine on my end. but should you hold off on merging until leah the speech functionality that works when you say "generate casual", "generate professional," "generate all" feature you mentioned? that's where we landed on that right - like we will have it?

**Review by thadakn1 — APPROVED** [review]
great work!

**Comment by sderacy** [comment]
I figure since I'm the only one who might want it, we can just skip adding it and move on

**Comment by paytonshaltis** [comment]
> I figure since I'm the only one who might want it, we can just skip adding it and move on

I think we all agree it's a good addition, we just want to keep what's there now that @lelekaz already had and just add the new functionality that you suggested @sderacy.

**Comment by sderacy** [comment]
Ask and ye shall receive 🎅🏾 

I added the shortcut commands. @paytonshaltis take a look at the mic icon changes because I think I understood what you were suggesting but I'm not sure if I implemented it in the way you wanted.

If you sign off on the shortcut commands and what I mentioned above, we can merge this in.

**Comment by paytonshaltis** [comment]
> I added the shortcut commands. @paytonshaltis take a look at the mic icon changes because I think I understood what you were suggesting but I'm not sure if I implemented it in the way you wanted.

I don't know if I'm not doing something right but none of the voice commands are working for me anymore like they were for @lelekaz in class the other day. Like not just the ones that you added @sderacy, but even the simple ones that Leah was showing off.

**Comment by sderacy** [comment]
> I don't know if I'm not doing something right but none of the voice commands are working for me anymore like they were for @lelekaz in class the other day. Like not just the ones that you added @sderacy, but even the simple ones that Leah was showing off.

Did you follow this? https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339

**Comment by paytonshaltis** [comment]
> Did you follow this? https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339

That wasn't the issue... I was trying it on my phone on Safari. Turns out, different browsers read the spoken words differently: Chrome doesn't add capital letters to the first word of the command whereas Safari does. I'm going to push a small commit rn that converts all of the words that were read in to lowercase; that should solve the issue.

**Comment by sderacy** [comment]
> Turns out, different browsers read the spoken words differently: Chrome doesn't add capital letters to the first word of the command whereas Safari does

Very cringe. Good find though, that ends up making this more robust

**Comment by paytonshaltis** [comment]
OK! I fixed the issue and checked on Safari both on my Mac and iPhone, everything is working well! Another small issue with the upper and lowercase came up for account labels that had uppercase letters, but I employed a similar fix using `toLowerCase()`.

A final issue that turned out to be a simple fix was that for Safari (and I'm assuming other OSes), after a QR code was generated, the speech recognition would bug out, likely due to the addition of a new DOM element. To fix this, anytime a user says one of the 4 generate commands (generate casual, professional, all, or just plain generate), the microphone button is automatically 'clicked' to end their speech session. 

Besides fixing the bug, it feels natural to end voice commands once a QR code has been generated, since realistically, nothing more needs to be said until the user wants to generate a new code. Try it out and see what you think, but it seems like a compromise between what @lelekaz @thadakn1 and I wanted (persisting mic) and what @sderacy wanted (auto-ending mic).

**Review by paytonshaltis — APPROVED** [review]
I approve, but someone else should check out those changes I just made.

**Comment by sderacy** [comment]
LGTM, I'm merging this in now. I think the auto-ending mic makes more sense in just those cases than in all the cases so good call on that too.

**Pull request merged**
