### PR TITLE
Add settings and profile page

### PR DESCRIPTION
**Pull request by sderacy**
I imagined that we would need to have a settings page to manipulate the accessible settings and we will also need a profile page to manipulate the social media links. This PR adds the routing for both, but you'll notice that they look very similar to the home page. The home page's links have been revamped since the links there originally didn't do anything. As we get closer to the bare functionality of this app, I'm changing the navbar to look like it should for the final version.

If possible, can you let me know how this looks on mobile? Especially the profile links.

### CODE REVIEW

**Comment by sderacy** [comment]
Almost forgot to mention, I added a new npm command called "cleanStart" which runs the seed command and start since I got tired of having to enter both commands manually. The readme should probably be updated to encompass that

**Comment by paytonshaltis** [comment]
> I imagined that we would need to have a settings page to manipulate the accessible settings and we will also need a profile page to manipulate the social media links. This PR adds the routing for both, but you'll notice that they look very similar to the home page. The home page's links have been revamped since the links there originally didn't do anything. As we get closer to the bare functionality of this app, I'm changing the navbar to look like it should for the final version.
> 
> If possible, can you let me know how this looks on mobile? Especially the profile links.
>
Good changes, the routing is working as expected with the middleware which is what we want. I did run into a small issue with the menu on desktop where the dropdown cuts off:

Screen Shot 2022-10-27 at 12 13 10 PM

Other than that, here's what it currently looks like on a mobile width:

Screen Shot 2022-10-27 at 12 34 27 PM

The dropdown is vertically centered (not sure if that was the intention) and the footer seems to overlap with the content. Adding a background to the footer would solve that issue. One final nitpick is that the hamburger menu button is probably too far left. Again these are all small issues, but they may be worth addressing either now or in a new issue.

One last thing: The dropdowns at mobile width on the settings and profile pages don't work, but they do on desktop. Not sure if you wanted to fix that for this commit or save it for another issue; let me know what would work best for you.

**Comment by paytonshaltis** [comment]
Since we had a lot of the same middleware code, I decided to move it to its own file and have pages that need it import it in.

**Comment by sderacy** [comment]
> Thanks for making the middleware changes. The mobile dropdown you're seeing is because I forgot to change the navbars on the other pages, so I should find a better way of maintaining all of those

I just pushed code up right now so you can take a look at it too but this is what's most likely going to happen for our project.

**Comment by paytonshaltis** [comment]
The partial relative links are fixed with the latest commit.

**Comment by sderacy** [comment]
You can approve it now if you want to, but I am noticing that it's not formatting my code when I run `npm run format`. We should look into that.

**Comment by sderacy** [comment]
It could also just be an issue on my side so I'm looking into it on my own

**Review by paytonshaltis — APPROVED** [review]
New pages and partial routing are all working well.

**Comment by sderacy** [comment]
I'll merge this and add an issue for the footer problem

**Pull request merged**
