### PR TITLE
Add font settings

### LINKED ISSUE #7: Provide font size changing
Allow user to change fonts to a specified value.

### LINKED ISSUE #107: Implement font size and family on settings and about us pages.
The last two pages that require the implementation of font size and family settings are the settings and about us pages. Once this is done, contrast and theme in issues #91 and #92 need to be implemented on all pages.

### PR DESCRIPTION
**Pull request by sderacy**
This adds the font size and font family settings to each home page except for the ones where the user may not necessarily be logged in.

Closes #7 and Closes #107

### CODE REVIEW

**Comment by sderacy** [comment]
Although the set attribute is advised against because it overwrites CSS properties, I couldn't find another way to implement this. It's also not a big deal because at the end of the day if there are multiple font families, it should always choose the one entered by the user.

**Comment by thadakn1** [comment]
i just tested it out on my end! it looks great!!

**Comment by sderacy** [comment]
The font size is implemented and the reason it's worded like that is because specifically in regards to font size, "smaller, medium, larger" are specific keywords that change the font size tag

I do agree that at least what they look like in the box should be changed

**Comment by thadakn1** [comment]
for some reason, i couldnt notice a difference with the font size, let me try it again. is it supposed to be a subtle difference?

**Comment by sderacy** [comment]
It changes the font by 1 rem, so you should be able to see it

**Comment by sderacy** [comment]
You can check to see if it was applied by going to the inspect element and seeing if the style was applied to the HTML element

**Comment by thadakn1** [comment]
leah and i both just checked, we didn't see any changes regarding the font size on our end. we both used the inspect tool and didn't see a change in the font size there either

**Comment by sderacy** [comment]
It should be fixed now @thadakn1 @lelekaz , please check it out now

**Review by thadakn1 — APPROVED** [review]
Great work!!

**Pull request merged**
