### PR TITLE
Implements issue #137 and #153.

### PR DESCRIPTION
**Pull request by lelekaz**

### CODE REVIEW

**Comment by sderacy** [comment]
@lelekaz in the future (if we even get that far since we finished mostly everything), just include "Closes #137, Closes #153" so someone else can hover over the number to see what you're referring to. I'm a little busy so I'm probably gonna look at this tomorrow night.

**Comment by paytonshaltis** [comment]
Looks great @lelekaz ! I added one small commit that removes the warning if the user tries submitting a form, since that was technically taking them to another page, it also popped the warning. Approving now...

**Review by paytonshaltis — APPROVED** [review]

**Review by sderacy — APPROVED** [review]
LGTM, I had to push a commit because I encountered this error again:

image

It works now but figured I should give a heads up.

**Comment by sderacy** [comment]
I think we can merge this one and #149 before Monday. I think they're good changes that are small but good for the quality of life aspect of the app.

**Comment by paytonshaltis** [comment]
> LGTM, I had to push a commit because I encountered this error again

Ah, this is what you were talking about in #151!

**Pull request merged**
