### PR TITLE
Finish up ReadMe Documentation

### LINKED ISSUE #148: Update ReadMe
Save this for later, but look over ReadMe once the application is ready to ship.

### PR DESCRIPTION
**Pull request by sderacy**
Closes #148 

Make sure the ReadMe is wrapped up with all the information relevant to our project.

### CODE REVIEW

**Comment by paytonshaltis** [comment]
Note to @paytonshaltis and @matyis1 to finish adding routes to readme after #65 is completed.

**Comment by paytonshaltis** [comment]
Before this gets merged, we should have another look at the final assignment document on Canvas to make sure that we have everything that she asked for in the readme, including detailed installation instructions, new programmer info, etc.

**Comment by sderacy** [comment]
@paytonshaltis Thanks for heads up. I moved things around so that it reads better, so feel free to take a look. I would tried to merge some things where I could but I ultimately just made a bigger header that encompasses all of the sections. I don't think we should try and merge them because while every section does not have a lot of info, they are distinct enough that they should be separated. I'm going to push another commit up to fix the TOC header at the top as well.

**Comment by sderacy** [comment]
@nishatreddy @thadakn1 could you take another look at the use cases too?

**Comment by thadakn1** [comment]
@sderacy i looked at the use cases, it looks good. i don't think there's anything else to add there. however, i did add some more accessibility stuff and pushed it up to the FinishupReadMeDocumentation branch. i may have not pushed to the pull request, but if its not there, thats fine. i just thought we'd add some about accessibility. lmk what you think. i think you can see those changes in the actual branch itself -- not the PR commit history.

**Comment by sderacy** [comment]
> @sderacy i looked at the use cases, it looks good. i don't think there's anything else to add there. however, i did add some more accessibility stuff and pushed it up to the FinishupReadMeDocumentation branch. i may have not pushed to the pull request, but if its not there, thats fine. i just thought we'd add some about accessibility. lmk what you think. i think you can see those changes in the actual branch itself -- not the PR commit history. if it doesn't show up for you, its fine, we can just merge regardless. it wasn't anything major but i added another guideline source and some intro on why we were accessibility focused.
> 
> im going to be out now so i cant work on it, but i can take a look at stuff if theres an issue with what i pushed once im back. but its totally cool if you just wanna merge without that stuff i added.

I don't see that branch, did you push that up to github?

**Comment by nishatreddy** [comment]
@sderacy yeah i did, this is what i see when i log into my personal github account. it says my other one pushed
Screen Shot 2022-12-02 at 9 30 14 PM
Screen Shot 2022-12-02 at 9 30 23 PM
Screen Shot 2022-12-02 at 9 30 33 PM

**Comment by sderacy** [comment]
@paytonshaltis If everything looks good you can approve this and we can ship it

**Comment by paytonshaltis** [comment]
Looks good, approving now.

**Review by paytonshaltis — APPROVED** [review]

**Pull request merged**
