### PR TITLE
Add qrcode endpoint

### LINKED ISSUE #1: QR Code Generation
User must be able to generate a QR code through a button/operation in the application.

This QR code will need to be persist for a set amount of time.

### LINKED ISSUE #40: Create API endpoint for creating qr code links.
When the user wants to create a QR code, they need to send a GET request to the server at:

`POST /home/generate`

When calling this API, you should pass an array of the IDs in the `user_accounts` table representing all of the accounts to be included. The API will create the necessary entries in the `card_entries` table with a new UUID, returning this UUID to the caller.

The IDs for the `user_accounts` will obviously be sent to the page when it is rendered; each user will see all of their name/link pairs that they can toggle, but their database IDs will also be there and sent to the endpoint when it is called.

### PR DESCRIPTION
**Pull request by paytonshaltis**
Closes #1, closes #40.

This PR uses the new `card_entries` table to add entries anytime the user clicks 'generate' on the home screen. The backend API is called, a unique UUID for that card is generated and stored in the database, and the UUID is returned to the client. The QR code can then be generated with this ID, and the user can navigate to the card page. Currently, the accounts are not showing up on the page, but this is a task for issue #113.

When generating a QR code, an alert pops up with the URL (also logged to the console) which is useful now for testing since not everyone's phone is working with the application. You can just copy and paste this into your browser on your computer to test the link.

I definitely recommend testing this one out on your own computers.

### CODE REVIEW

**Comment by sderacy** [comment]
@paytonshaltis You have a merge conflict here. Take another look at your toggle code now that Leah's code has been merged in.

I'd do it myself but I wanna make sure I don't ruin any functionality you have.

Once that's done, I take a closer look at it.

**Review by sderacy — COMMENTED** [review]
Code looks good overall, just wanna wait for the conflict to be resolved before testing it out

**Comment by paytonshaltis** [comment]
> @paytonshaltis You have a merge conflict here. Take another look at your toggle code now that Leah's code has been merged in.

Yeah, Leah's changes weren't in `main` by the time I made this PR... conflicts were simple enough to fix, feel free to test now and let me know if something isn't working how you'd expect it.

**Comment by sderacy** [comment]
The generate button is disabled:
image

I made sure to remove the node_modules folder and installing the packages so do you know what this might be caused by?

**Comment by sderacy** [comment]
Update: It seems to happen only when you press the buttons at the top.

**Comment by sderacy** [comment]
Also I can't test the QR code path on my laptop since I can't run it on my phone, but I can see that it's generating the uuid.

**Comment by sderacy** [comment]
@matyis1 @lelekaz @thadakn1 
If you've encountered the issue where your phone is not able to access the server on your computer, I would double check your firewall settings.

I got mine to work by turning off my firewall, which means something specifically is denying my phone access.

It makes sense why I could connect to Payton's laptop and not my own.

Just a heads up.

**Review by sderacy — CHANGES_REQUESTED** [review]
Can we see how to fix that bug I mentioned before merging?

It worked btw, it looked really good :)

**Review by sderacy — APPROVED** [review]
Just decided to fix it myself.

Looks good! Ship it.

**Pull request merged**
